### ISSUE TITLE
对比算法的性能写的偏低了。。。

### ISSUE THREAD

**Issue by hermosayhl** [lin-zhao-resoLve/Deep-Symmetric-Network-Enhancement#1]
经过我多次的实验，FiveK 数据集，4500 训练（其中 500 valid），500 测试

DeepLPF 大概      24.5 - 25.0db 左右的性能
CSRNet 大概        25.0 - 25.3db 左右的性能
DPE(paired)大概  23.5 - 24.0db 左右的性能
HDRNet 大概       24.0 - 24.5db 左右的性能

而且，还有 3D-LUT(25.2db) 和 GleNet(25.0db)，MIRNet((24.80db) 等 SOTA 算法没有比

**Comment by lin-zhao-resoLve** [comment]
您好，请问您用的是原始的FiveK数据集还是我们文章中提到的改进后的FiveK数据集？数据集不同结果会有一定差异．

**Comment by hermosayhl** [comment]
> 您好，请问您用的是原始的FiveK数据集还是我们文章中提到的改进后的FiveK数据集？数据集不同结果会有一定差异．
您也好。没想到会被回复。我记得，fiveK 数据集，paired training 有两种分法。一种是 DeepPhotoEnhancer，分 4500 训练，500 测试（这种分法，有几篇如 DeepLPF，4500 里分出 500 做验证 valid）。还有一种是 Distort-and-recover 4500 训练，剩下 500，250 做 valid，250 做 test。这个 repo 的算法使用的是后一种。我使用的前一种，前一种更多论文采用。即使数据从500 变成 250，那几个对比算法的性能也不会那么低的，甚至 0.1-0.2db 的差别。

**Comment by hermosayhl** [comment]
> 您好，请问您用的是原始的FiveK数据集还是我们文章中提到的改进后的FiveK数据集？数据集不同结果会有一定差异．

在 DeepLPF 论文 4.1 章节，Experiments 也分了两种 DPE 和 UPE

**Comment by lin-zhao-resoLve** [comment]
Distort-and-recover数据集的低质量图像与原数据集是不同的，并不只是划分方式不同．

**Comment by hermosayhl** [comment]
> Distort-and-recover数据集的低质量图像与原数据集是不同的，并不只是划分方式不同．

请问是调了白平衡 1.5 吗？
