### ISSUE TITLE
lol checkpoint issue

### ISSUE THREAD

**Issue by Li-Chongyi** [lin-zhao-resoLve/Deep-Symmetric-Network-Enhancement#5]
Hi Authors,

The provided lol model cannot produce correct results. Any suggestions would be appreciated. Thanks!
![02bcc777e7aff5facb8d6e67619861b](https://user-images.githubusercontent.com/34166801/179344735-78681dbf-cdd3-4f15-9fb5-d1d2e17d764f.png)

**Comment by zhanggengchen** [comment]
I have the same problem ...
![1_sym](https://user-images.githubusercontent.com/44341192/187861546-5e472d5c-948f-4cc9-ac9c-7cd2475fbc48.png)

**Comment by szxmachinelearning** [comment]
我也是同样的问题，这都不维护一下的嘛？按理来说应该自己跑一下吧......
